# Generated by Django 4.0.6 on 2022-08-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_question_photo_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='timer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
