# Generated by Django 4.0.6 on 2022-08-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_combinedqanda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.question'),
        ),
        migrations.DeleteModel(
            name='CombinedQandA',
        ),
    ]
