# Generated by Django 4.0.6 on 2022-08-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_points_remove_answer_points_remove_answer_timer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='ans_id',
            field=models.IntegerField(default=None),
        ),
    ]
