# Generated by Django 4.0.6 on 2022-08-10 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0009_alter_points_ans_id_alter_points_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='group',
        ),
        migrations.RemoveField(
            model_name='points',
            name='points',
        ),
        migrations.RemoveField(
            model_name='points',
            name='question',
        ),
        migrations.RemoveField(
            model_name='points',
            name='test',
        ),
        migrations.AlterField(
            model_name='points',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_answerid', to='quizzes.answer'),
        ),
        migrations.AlterField(
            model_name='points',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
