# Generated by Django 4.0.6 on 2022-08-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_remove_points_group_remove_points_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='points',
            name='user',
        ),
    ]
